title: ManualEvents
modelClass: artandcodestudio\Facebookevents\Models\ManualEvents
list: $/artandcodestudio/facebookevents/models/manualevents/columns.yaml
recordUrl: 'artandcodestudio/facebookevents/manualevents/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
