plugin:
  name: 'ArtAndCodeStudio.facebookevents::lang.plugin.name'
  description: 'artandcodestudio.facebookevents::lang.plugin.description'
  author: 'Art+Code Studio'
  icon: oc-icon-facebook
homepage: 'https://artandcode.studio/'
navigation:
  ManualEvents:
    label: ManualEvents
    url: artandcodestudio/facebookevents/manualevents
    icon: icon-flash
