plugin:
    name: 'ArtAndCodeStudio.facebookevents::lang.plugin.name'
    description: 'artandcodestudio.facebookevents::lang.plugin.description'
    author: artandcodestudio
    icon: oc-icon-facebook
    homepage: ''
