plugin:
  name: 'FacebookEvents'
  description: 'Add FacebookEvents from a Facebook-Page'
  author: 'Art+Code Studio'
  icon: oc-icon-facebook
homepage: 'https://artandcode.studio/'
navigation:
  ManualEvents:
    label: ManualEvents
    url: artandcodestudio/facebookevents/manualevents
    icon: icon-flash
